{"Example.js":[{"testName":"Test valid name","path":"out\\Example.js","message":"OK","passed":true},{"testName":"Test fail","path":"out\\Example.js","message":"{\"generatedMessage\":false,\"name\":\"AssertionError [ERR_ASSERTION]\",\"code\":\"ERR_ASSERTION\",\"actual\":false,\"expected\":true,\"operator\":\"==\",\"stackMessage\":\"AssertionError [ERR_ASSERTION]: One should be more than two!\\n    at TestCase.True (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Test\\\\Test.js:54:16)\\n    at Test_1.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Example.js:21:10)\\n    at Object.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Test\\\\Test.js:69:9)\\n    at Object.<anonymous> (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Example.js:20:8)\\n    at Module._compile (module.js:635:30)\\n    at Object.Module._extensions..js (module.js:646:10)\\n    at Module.load (module.js:554:32)\\n    at tryModuleLoad (module.js:497:12)\\n    at Function.Module._load (module.js:489:3)\\n    at Function.Module.runMain (module.js:676:10)\",\"errorMessage\":\"One should be more than two!\"}","passed":false},{"testName":"Test changed name","path":"out\\Example.js","message":"OK","passed":true},{"testName":"Test valid name","path":"out\\src\\Example.js","message":"OK","passed":true},{"testName":"Test fail","path":"out\\src\\Example.js","message":"{\"generatedMessage\":false,\"name\":\"AssertionError [ERR_ASSERTION]\",\"code\":\"ERR_ASSERTION\",\"actual\":false,\"expected\":true,\"operator\":\"==\",\"stackMessage\":\"AssertionError [ERR_ASSERTION]: One should be more than two!\\n    at TestCase.True (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Test\\\\Test.js:54:16)\\n    at Test_1.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Example.js:21:10)\\n    at Object.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Test\\\\Test.js:69:9)\\n    at Object.<anonymous> (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Example.js:20:8)\\n    at Module._compile (module.js:635:30)\\n    at Object.Module._extensions..js (module.js:646:10)\\n    at Module.load (module.js:554:32)\\n    at tryModuleLoad (module.js:497:12)\\n    at Function.Module._load (module.js:489:3)\\n    at Function.Module.runMain (module.js:676:10)\",\"errorMessage\":\"One should be more than two!\"}","passed":false},{"testName":"Test changed name","path":"out\\src\\Example.js","message":"OK","passed":true}],"Sample.js":[{"testName":"Test fail","path":"out\\Sample.js","message":"{\"generatedMessage\":false,\"name\":\"AssertionError [ERR_ASSERTION]\",\"code\":\"ERR_ASSERTION\",\"actual\":false,\"expected\":true,\"operator\":\"==\",\"stackMessage\":\"AssertionError [ERR_ASSERTION]: One should be more than two!\\n    at TestCase.True (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Test\\\\Test.js:54:16)\\n    at Test_1.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Sample.js:8:10)\\n    at Object.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Test\\\\Test.js:69:9)\\n    at Object.<anonymous> (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Sample.js:7:8)\\n    at Module._compile (module.js:635:30)\\n    at Object.Module._extensions..js (module.js:646:10)\\n    at Module.load (module.js:554:32)\\n    at tryModuleLoad (module.js:497:12)\\n    at Function.Module._load (module.js:489:3)\\n    at Function.Module.runMain (module.js:676:10)\",\"errorMessage\":\"One should be more than two!\"}","passed":false},{"testName":"Test fail","path":"out\\src\\Sample.js","message":"{\"generatedMessage\":false,\"name\":\"AssertionError [ERR_ASSERTION]\",\"code\":\"ERR_ASSERTION\",\"actual\":false,\"expected\":true,\"operator\":\"==\",\"stackMessage\":\"AssertionError [ERR_ASSERTION]: One should be more than two!\\n    at TestCase.True (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Test\\\\Test.js:54:16)\\n    at Test_1.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Sample.js:8:10)\\n    at Object.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Test\\\\Test.js:69:9)\\n    at Object.<anonymous> (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Sample.js:7:8)\\n    at Module._compile (module.js:635:30)\\n    at Object.Module._extensions..js (module.js:646:10)\\n    at Module.load (module.js:554:32)\\n    at tryModuleLoad (module.js:497:12)\\n    at Function.Module._load (module.js:489:3)\\n    at Function.Module.runMain (module.js:676:10)\",\"errorMessage\":\"One should be more than two!\"}","passed":false}],"One.js":[{"testName":"Test increment","path":"out\\One\\One.js","message":"{\"generatedMessage\":true,\"name\":\"AssertionError [ERR_ASSERTION]\",\"code\":\"ERR_ASSERTION\",\"actual\":10,\"expected\":9,\"operator\":\"===\",\"stackMessage\":\"AssertionError [ERR_ASSERTION]: 10 === 9\\n    at TestCase.StrictEquals (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Test\\\\Test.js:28:16)\\n    at Test_1.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\One\\\\One.js:8:10)\\n    at Object.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\Test\\\\Test.js:69:9)\\n    at Object.<anonymous> (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\One\\\\One.js:4:8)\\n    at Module._compile (module.js:635:30)\\n    at Object.Module._extensions..js (module.js:646:10)\\n    at Module.load (module.js:554:32)\\n    at tryModuleLoad (module.js:497:12)\\n    at Function.Module._load (module.js:489:3)\\n    at Function.Module.runMain (module.js:676:10)\",\"errorMessage\":\"10 === 9\"}","passed":false},{"testName":"Test increment","path":"out\\src\\One\\One.js","message":"{\"generatedMessage\":true,\"name\":\"AssertionError [ERR_ASSERTION]\",\"code\":\"ERR_ASSERTION\",\"actual\":41,\"expected\":40,\"operator\":\"===\",\"stackMessage\":\"AssertionError [ERR_ASSERTION]: 41 === 40\\n    at TestCase.StrictEquals (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Test\\\\Test.js:28:16)\\n    at Test_1.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\One\\\\One.js:8:10)\\n    at Object.Test (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\Test\\\\Test.js:69:9)\\n    at Object.<anonymous> (C:\\\\Users\\\\admin\\\\Documents\\\\Personal Projects\\\\MyoTest\\\\out\\\\src\\\\One\\\\One.js:4:8)\\n    at Module._compile (module.js:635:30)\\n    at Object.Module._extensions..js (module.js:646:10)\\n    at Module.load (module.js:554:32)\\n    at tryModuleLoad (module.js:497:12)\\n    at Function.Module._load (module.js:489:3)\\n    at Function.Module.runMain (module.js:676:10)\",\"errorMessage\":\"41 === 40\"}","passed":false}],"DirStructureTest.js":[{"testName":"Test structure has test","path":"out\\tests\\Report\\DirStructureTest.js","message":"OK","passed":true}]}